
cu_cp:
  amf:
    addr: 192.168.70.132
    port: 38412
    bind_addr: 192.168.70.129
    supported_tracking_areas:
      - tac: 1
        plmn_list:
          - plmn: "00101"
            tai_slice_support_list:
              - sst: 1
  inactivity_timer: 7200
  request_pdu_session_timeout: 120
  rrc:
    rrc_procedure_guard_time_ms: 12800

cu_up:
  ngu:
    socket:
      - bind_addr: 192.168.70.129

ru_sdr:
  device_driver: rfsimulator
  device_args: serveraddr=server,serverport=4043,prop_delay=119.36926,realtime
  srate: 15.36
  tx_gain: 0
  rx_gain: 0

cell_cfg:
  dl_arfcn: 437000
  band: 256
  channel_bandwidth_MHz: 10
  common_scs: 15
  plmn: "00101"
  tac: 1
  nof_antennas_dl: 1
  nof_antennas_ul: 1
  slicing:
    - sst: 1

  sib:
    t300: 2000
    t301: 2000
    t311: 3000
    t319: 2000
    si_window_length: 40
    si_sched_info:
      - si_period: 16
        sib_mapping: 2
      - si_period: 16
        sib_mapping: 19
        si_window_position: 2
    sib2:
      q_hyst: 3
      thresh_serving_low_p: 0
      cell_reselection_priority: 6
      q_rx_lev_min: -140
      s_intra_search_p: 62
      t_reselection_nr: 1

  pucch:
    sr_period_ms: 80
    max_consecutive_kos: 100000
    resource_set_size: 7
    nof_cell_res_set_configs: 1
    f1_nof_cyclic_shifts: 1
    f1_enable_occ: true
    nof_cell_sr_res: 7
    nof_cell_csi_res: 7

  csi:
    csi_rs_period: 80

  mac_cell_group:
    sr_cfg:
      sr_prohibit_timer: 128
      sr_trans_max: 64

  pdsch:
    harq_retx_timeout: 500
    nof_harqs: 16
    max_nof_harq_retxs: 0
    harq_feedback_disabled: true

  pusch:
    harq_retx_timeout: 500
    max_nof_harq_retxs: 0
    harq_mode_b: true

  prach:
    prach_config_index: 44
    max_msg3_harq_retx: 0

  ta:
    ta_cmd_offset_threshold: 1
    ta_measurement_slot_period: 40
    ta_measurement_slot_prohibit_period: 250
    ta_target: 0

  ntn:
    epoch_timestamp: '2026-09-02T15:27:52'
    propagator_type: keplerian
    cell_specific_koffset: 240
    ntn_ul_sync_validity_dur: 240
    use_state_vector: true
    reference_location:
      latitude: 0.0
      longitude: 0.0
    ephemeris_info_ecef:
      pos_x: 42164140
      pos_y: 0
      pos_z: 0
      vel_x: 0
      vel_y: 0
      vel_z: 0

srbs:
  - srb_id: 1
    mac:
      triggered_ul_grant:
        delay: 16
    rlc:
      tx:
        sn: 12
        t-poll-retransmit: 1000
        max-retx-threshold: 32
        poll-pdu: -1
        poll-byte: -1
      rx:
        sn: 12
        t-reassembly: 200
        t-status-prohibit: 10
  - srb_id: 2
    rlc:
      tx:
        sn: 12
        t-poll-retransmit: 1000
        max-retx-threshold: 32
        poll-pdu: -1
        poll-byte: -1
      rx:
        sn: 12
        t-reassembly: 200
        t-status-prohibit: 10

log:
  filename: /tmp/gnb_geo.log
  all_level: info
  ntn_level: info
  broadcast_enabled: false
  hex_max_size: 256

pcap:
  mac_enable: false
  mac_filename: /tmp/ntn_geo_mac.pcap
  ngap_enable: false
  ngap_filename: /tmp/ntn_geo_ngap.pcap
