cell_cfg:
  sib:
    t300: 2000
    t301: 2000
    t311: 3000
    t319: 2000
    si_window_length: 40
    si_sched_info:
      - si_period: 16
        sib_mapping: 2
      - si_period: 16
        sib_mapping: 19
        si_window_position: 2
    sib2:
      q_hyst: 3
      thresh_serving_low_p: 0
      cell_reselection_priority: 6
      q_rx_lev_min: -140
      s_intra_search_p: 62
      t_reselection_nr: 1
  pucch:
    sr_period_ms: 80
    max_consecutive_kos: 100000
  csi:
    csi_rs_period: 80
  mac_cell_group:
    sr_cfg:
      sr_prohibit_timer: 128
      sr_trans_max: 64
  pdsch:
    harq_retx_timeout: 500
    nof_harqs: 16
    max_nof_harq_retxs: 0
    harq_feedback_disabled: true
  pusch:
    harq_retx_timeout: 500
    max_nof_harq_retxs: 0
    harq_mode_b: true
  prach:
    prach_config_index: 44
    max_msg3_harq_retx: 0
  ta:
    ta_cmd_offset_threshold: -1
    ta_measurement_slot_period: 40
    ta_measurement_slot_prohibit_period: 250
    ta_target: 0
  ntn:
    epoch_timestamp: '2026-01-01T00:00:00'
    propagator_type: keplerian
    cell_specific_koffset: 40
    ntn_ul_sync_validity_dur: 5
    use_state_vector: true
    feeder_link:
      enable_doppler_compensation: false
      dl_freq: 27500000000.0
      ul_freq: 17800000000.0
    gateway_location:
      latitude: -2.2817
      longitude: 131.7327
      altitude: 0.0
    ephemeris_info_ecef:
      pos_x: -4636611.2
      pos_y: 5198042.2
      pos_z: -277534.4
      vel_x: -200.4
      vel_y: 224.64
      vel_z: 7555.74
cu_cp:
  request_pdu_session_timeout: 120
  rrc:
    rrc_procedure_guard_time_ms: 12800

srbs:
  - srb_id: 1
    mac:
      triggered_ul_grant:
        delay: 16
    rlc:
      tx:
        sn: 12
        t-poll-retransmit: 1000
        max-retx-threshold: 32
        poll-pdu: -1
        poll-byte: -1
      rx:
        sn: 12
        t-reassembly: 200
        t-status-prohibit: 10
  - srb_id: 2
    rlc:
      tx:
        sn: 12
        t-poll-retransmit: 1000
        max-retx-threshold: 32
        poll-pdu: -1
        poll-byte: -1
      rx:
        sn: 12
        t-reassembly: 200
        t-status-prohibit: 10
