#!/usr/bin/env python3
import argparse
import csv
import glob
import json
import math
import os
import sys

os.environ.setdefault("OMP_NUM_THREADS", "4")
import numpy as np
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import brier_score_loss, roc_auc_score

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from ml_config import FEATURES, LABEL


def load(paths):
    rows = []
    for p in paths:
        with open(p, newline="") as fh:
            for r in csv.DictReader(fh):
                if all(r.get(c) not in (None, "") for c in FEATURES + ["nof_retxs", LABEL]):
                    rows.append(r)
    return rows


def build(rows):
    x = np.array([[float(r[c]) for c in FEATURES] for r in rows], dtype=np.float64)
    y = np.array([int(float(r[LABEL])) for r in rows], dtype=np.int32)
    return x, y


def time_split_dedup(rows, test_frac):
    cut = int(len(rows) * (1.0 - test_frac))
    xtr, ytr = build(rows[:cut])
    xte, yte = build(rows[cut:])
    seen = set()
    keep = np.ones(len(xtr), dtype=bool)
    for i, row in enumerate(map(tuple, np.column_stack([xtr, ytr]).tolist())):
        if row in seen:
            keep[i] = False
        else:
            seen.add(row)
    xtr, ytr = xtr[keep], ytr[keep]
    trf = set(map(tuple, xtr.tolist()))
    mask = np.array([tuple(r) not in trf for r in xte.tolist()]) if len(xte) else np.array([], bool)
    return xtr, ytr, xte[mask], yte[mask]


def model_arrays(model):
    lr = float(model.learning_rate)
    prior = float(model.init_.class_prior_[1])
    init = math.log(prior / (1.0 - prior))
    off, feat, thr, left, right, val = [], [], [], [], [], []
    base = 0
    for stage in model.estimators_:
        t = stage[0].tree_
        off.append(base)
        for i in range(t.node_count):
            lc, rc = int(t.children_left[i]), int(t.children_right[i])
            feat.append(int(t.feature[i]))
            thr.append(float(t.threshold[i]))
            left.append(base + lc if lc >= 0 else -1)
            right.append(base + rc if rc >= 0 else -1)
            val.append(float(t.value[i][0][0]))
        base += t.node_count
    off.append(base)
    return lr, init, off, feat, thr, left, right, val


def export_inc(model, out_path, meta):
    lr, init, off, feat, thr, left, right, val = model_arrays(model)
    n_nodes = sum(len(stage[0].tree_.feature) for stage in model.estimators_)
    lines = []
    a = lines.append
    a("// SPDX-License-Identifier: BSD-3-Clause-Open-MPI")
    a("// AUTO-GENERATED by ml/training/train_export_mcs.py - DO NOT EDIT BY HAND.")
    a(f"// Source: {meta['sources']}")
    a(f"// Rows: {meta['rows']}  held-out AUC: {meta['auc']:.4f}  Brier: {meta['brier']:.4f}")
    a(f"// Features (in order): {FEATURES}")
    a("#pragma once")
    a("#include <cstdint>")
    a("#include <cmath>")
    a("namespace ocudu {")
    a("namespace mcs_ml {")
    a(f"inline constexpr int    NUM_FEATURES  = {len(FEATURES)};")
    a(f"inline constexpr int    NUM_TREES     = {len(model.estimators_)};")
    a(f"inline constexpr double LEARNING_RATE = {lr!r};")
    a(f"inline constexpr double INIT_LOGODDS  = {init!r};")
    for idx, name in enumerate(FEATURES):
        a(f"inline constexpr int FEAT_{name.upper()} = {idx};")

    def emit_int(name, arr):
        a(f"inline constexpr int {name}[{len(arr)}] = {{{','.join(str(x) for x in arr)}}};")

    def emit_dbl(name, arr):
        a(f"inline constexpr double {name}[{len(arr)}] = {{{','.join(repr(x) for x in arr)}}};")

    emit_int("TREE_OFFSET", off)
    emit_int("NODE_FEATURE", feat)
    emit_dbl("NODE_THRESHOLD", thr)
    emit_int("NODE_LEFT", left)
    emit_int("NODE_RIGHT", right)
    emit_dbl("NODE_VALUE", val)
    a("""
inline double predict_proba(const double* feat)
{
  double score = INIT_LOGODDS;
  for (int t = 0; t < NUM_TREES; ++t) {
    int node = TREE_OFFSET[t];
    while (NODE_LEFT[node] >= 0) {
      node = (feat[NODE_FEATURE[node]] <= NODE_THRESHOLD[node]) ? NODE_LEFT[node] : NODE_RIGHT[node];
    }
    score += LEARNING_RATE * NODE_VALUE[node];
  }
  return 1.0 / (1.0 + std::exp(-score));
}
} // namespace mcs_ml
} // namespace ocudu""")
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return n_nodes


def export_model_file(model, path, meta):
    lr, init, off, feat, thr, left, right, val = model_arrays(model)
    blob = {
        "format": "ocudu_mcs_ml",
        "version": 1,
        "num_features": len(FEATURES),
        "features": FEATURES,
        "num_trees": len(model.estimators_),
        "learning_rate": lr,
        "init_logodds": init,
        "tree_offset": off,
        "node_feature": feat,
        "node_threshold": thr,
        "node_left": left,
        "node_right": right,
        "node_value": val,
        "meta": meta,
    }
    with open(path, "w") as fh:
        json.dump(blob, fh)


def train(rows, n_estimators, max_depth, lr, test_frac):
    xtr, ytr, xte, yte = time_split_dedup(rows, test_frac)
    model = GradientBoostingClassifier(
        n_estimators=n_estimators, max_depth=max_depth, learning_rate=lr, subsample=0.8, random_state=0
    )
    model.fit(xtr, ytr)
    p = model.predict_proba(xte)[:, 1]
    auc = roc_auc_score(yte, p)
    brier = brier_score_loss(yte, p)
    xall, yall = build(rows)
    final = GradientBoostingClassifier(
        n_estimators=n_estimators, max_depth=max_depth, learning_rate=lr, subsample=0.8, random_state=0
    )
    final.fit(xall, yall)
    return final, auc, brier, len(ytr), len(yte)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("csv", nargs="*")
    ap.add_argument("--out", required=True)
    ap.add_argument("--model-out", default=None)
    ap.add_argument("--n-estimators", type=int, default=200)
    ap.add_argument("--max-depth", type=int, default=4)
    ap.add_argument("--lr", type=float, default=0.08)
    ap.add_argument("--test-frac", type=float, default=0.2)
    args = ap.parse_args()

    if args.out.endswith(".csv"):
        sys.exit(f"refusing to write generated code to a .csv path: {args.out}")

    paths = args.csv or sorted(glob.glob("ml/datasets/ul_mcs_dataset_*.csv"))
    rows = [r for r in load(paths) if int(float(r["nof_retxs"])) == 0]
    if len(rows) < 1000:
        sys.exit(f"not enough newTx rows: {len(rows)}")
    print(f"files={len(paths)} newTx_rows={len(rows)}")

    model, auc, brier, ntr, nte = train(rows, args.n_estimators, args.max_depth, args.lr, args.test_frac)
    print(f"held-out (dedup, leakage-safe): AUC={auc:.4f} Brier={brier:.4f} train={ntr} test={nte}")

    meta = {"sources": [os.path.basename(p) for p in paths], "rows": len(rows), "auc": auc, "brier": brier}
    n = export_inc(model, args.out, meta)
    model_out = args.model_out or (args.out + ".model")
    export_model_file(model, model_out, meta)
    print(f"exported {len(model.estimators_)} trees ({n} nodes) -> {args.out}")
    print(f"exported runtime model -> {model_out}")


if __name__ == "__main__":
    main()
