#!/usr/bin/env python3
import argparse
import glob
import json
import os
import sys

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from csi_ml_config import WINDOW_SIZE

from train_export_csi_wiener import (
    _LICENSE,
    build_dataset,
    evaluate,
    load_series,
    time_split,
)

def _require_torch():
    try:
        import torch
    except ImportError:
        sys.exit(
            "PyTorch is required to train the GRU model (pip install torch). The Wiener model "
            "(train_export_csi_wiener.py) has no such dependency if you want to avoid it."
        )
    import torch
    return torch

class CsiGRU:

    def __init__(self, torch, d, t_out, seed=0):
        self.torch = torch
        self.d = d
        self.t_out = t_out
        g = torch.Generator().manual_seed(seed)

        def rand(*shape):

            fan_in = shape[-1]
            bound = 1.0 / max(1.0, np.sqrt(fan_in))
            return (torch.rand(*shape, generator=g) * 2 - 1) * bound

        self.W_z, self.U_z, self.b_z = rand(d, 1), rand(d, d), torch.zeros(d)
        self.W_r, self.U_r, self.b_r = rand(d, 1), rand(d, d), torch.zeros(d)
        self.W_h, self.U_h, self.b_h = rand(d, 1), rand(d, d), torch.zeros(d)
        self.W_out, self.b_out = rand(t_out, d), torch.zeros(t_out)
        self.params = [self.W_z, self.U_z, self.b_z, self.W_r, self.U_r, self.b_r,
                       self.W_h, self.U_h, self.b_h, self.W_out, self.b_out]
        for p in self.params:
            p.requires_grad_(True)

    def forward(self, x):
        torch = self.torch
        batch, p = x.shape
        h = torch.zeros(batch, self.d)
        for t in range(p):
            xt = x[:, t : t + 1]
            z = torch.sigmoid(xt @ self.W_z.t() + h @ self.U_z.t() + self.b_z)
            r = torch.sigmoid(xt @ self.W_r.t() + h @ self.U_r.t() + self.b_r)
            hh = torch.tanh(xt @ self.W_h.t() + (r * h) @ self.U_h.t() + self.b_h)
            h = (1 - z) * h + z * hh
        return h @ self.W_out.t() + self.b_out

def train(torch, gru, xtr, ytr, epochs, batch_size, lr, seed=0):
    opt = torch.optim.Adam(gru.params, lr=lr)
    loss_fn = torch.nn.MSELoss()
    xt = torch.tensor(xtr, dtype=torch.float32)
    yt = torch.tensor(ytr, dtype=torch.float32)
    n = xt.shape[0]
    g = torch.Generator().manual_seed(seed)
    for epoch in range(epochs):
        perm = torch.randperm(n, generator=g)
        total = 0.0
        for i in range(0, n, batch_size):
            idx = perm[i : i + batch_size]
            opt.zero_grad()
            out = gru.forward(xt[idx])
            loss = loss_fn(out, yt[idx])
            loss.backward()
            opt.step()
            total += float(loss) * len(idx)
        if (epoch + 1) % max(1, epochs // 10) == 0 or epoch == 0:
            print(f"  epoch {epoch+1}/{epochs}  train_mse(std)={total/n:.5f}", file=sys.stderr)

def arrays(gru):
    def flat(t):
        return t.detach().numpy().astype(np.float64).reshape(-1).tolist()
    return {
        "w_z": flat(gru.W_z), "u_z": flat(gru.U_z), "b_z": flat(gru.b_z),
        "w_r": flat(gru.W_r), "u_r": flat(gru.U_r), "b_r": flat(gru.b_r),
        "w_h": flat(gru.W_h), "u_h": flat(gru.U_h), "b_h": flat(gru.b_h),
        "w_out": flat(gru.W_out), "b_out": flat(gru.b_out),
    }

def _fmt(name, arr):
    return f"inline constexpr double {name}[{len(arr)}] = {{{','.join(repr(float(x)) for x in arr)}}};"

def export_inc(a, mu, sigma, p, d, t_out, out_path):
    lines = [ln for ln in _LICENSE.split("\n") if ln] or []
    lines += [
        "// AUTO-GENERATED by ml/training/train_export_csi_gru.py — do not edit by hand.",
        "",
        "#pragma once",
        "namespace ocudu {",
        "namespace csi_ml {",
        "",
        f"inline constexpr unsigned GRU_SEED_P     = {int(p)};",
        f"inline constexpr unsigned GRU_SEED_D     = {int(d)};",
        f"inline constexpr unsigned GRU_SEED_T_OUT = {int(t_out)};",
        f"inline constexpr double   GRU_SEED_MU    = {float(mu)!r};",
        f"inline constexpr double   GRU_SEED_SIGMA = {float(sigma)!r};",
        "",
        _fmt("GRU_SEED_W_Z", a["w_z"]), _fmt("GRU_SEED_U_Z", a["u_z"]), _fmt("GRU_SEED_B_Z", a["b_z"]),
        _fmt("GRU_SEED_W_R", a["w_r"]), _fmt("GRU_SEED_U_R", a["u_r"]), _fmt("GRU_SEED_B_R", a["b_r"]),
        _fmt("GRU_SEED_W_H", a["w_h"]), _fmt("GRU_SEED_U_H", a["u_h"]), _fmt("GRU_SEED_B_H", a["b_h"]),
        _fmt("GRU_SEED_W_OUT", a["w_out"]), _fmt("GRU_SEED_B_OUT", a["b_out"]),
        "",
        "} // namespace csi_ml",
        "} // namespace ocudu",
    ]
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")

def export_model_file(a, mu, sigma, p, d, t_out, path, meta):
    blob = {
        "format": "ocudu_csi_gru", "version": 1,
        "p": int(p), "d": int(d), "t_out": int(t_out), "mu": float(mu), "sigma": float(sigma),
        **a, "meta": meta,
    }
    with open(path, "w") as fh:
        json.dump(blob, fh)

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("csv", nargs="*", help="dataset CSV(s); default: ml/datasets/csi_ml_dataset_*.csv")
    ap.add_argument("--window-size", type=int, default=WINDOW_SIZE, help=f"input window P (default: {WINDOW_SIZE})")
    ap.add_argument("--t-out", type=int, default=1, help="output horizons in reports ahead (default: 1)")
    ap.add_argument("--hidden", type=int, default=16, help="GRU hidden units D (default: 16)")
    ap.add_argument("--epochs", type=int, default=200, help="training epochs (default: 200)")
    ap.add_argument("--batch-size", type=int, default=2048, help="minibatch size (default: 2048)")
    ap.add_argument("--lr", type=float, default=0.01, help="Adam learning rate")
    ap.add_argument("--test-frac", type=float, default=0.3, help="chronological test split fraction")
    ap.add_argument("--seed", type=int, default=0, help="RNG seed")
    ap.add_argument("--inc-out", default=None, help="path to write the compiled-in C++ seed header")
    ap.add_argument("--model-out", default=None, help="path to write the runtime override .model (JSON)")
    ap.add_argument("--min-samples", type=int, default=200, help="minimum windowed samples required to train")
    args = ap.parse_args()

    torch = _require_torch()
    torch.manual_seed(args.seed)

    paths = args.csv or sorted(glob.glob("ml/datasets/csi_ml_dataset_*.csv"))
    if not paths:
        sys.exit("no dataset CSVs found (pass paths explicitly, or check ml/datasets/csi_ml_dataset_*.csv)")

    sessions = [load_series(p) for p in paths]
    x, y, flat = build_dataset(sessions, args.window_size, args.t_out)
    print(f"files={len(paths)} ues={sum(len(s) for s in sessions)} windowed_samples={len(y)} "
          f"window_size={args.window_size} t_out={args.t_out} hidden={args.hidden}")
    if len(y) < args.min_samples:
        sys.exit(f"not enough windowed samples: {len(y)} < --min-samples={args.min_samples}")

    mu = float(np.mean(flat))
    sigma = float(np.std(flat)) or 1.0
    print(f"standardization: mu={mu:.4f} sigma={sigma:.4f}")

    xtr, ytr, xte, yte = time_split(x, y, args.test_frac)
    if len(yte) == 0:
        sys.exit("test split is empty — increase samples or lower --test-frac")

    xtr_s = (xtr - mu) / sigma
    ytr_s = (ytr - mu) / sigma
    gru = CsiGRU(torch, args.hidden, args.t_out, seed=args.seed)
    print(f"training GRU (D={args.hidden}, epochs={args.epochs}, batch={args.batch_size})...")
    train(torch, gru, xtr_s, ytr_s, args.epochs, args.batch_size, args.lr, seed=args.seed)

    with torch.no_grad():
        pred_s = gru.forward(torch.tensor((xte - mu) / sigma, dtype=torch.float32)).numpy()
    ypred_h1 = pred_s[:, 0] * sigma + mu
    ytrue_h1 = yte[:, 0]
    zoh_h1 = xte[:, -1]
    m_ml = evaluate(ytrue_h1, ypred_h1, mu, sigma)
    m_zoh = evaluate(ytrue_h1, zoh_h1, mu, sigma)
    print("\nHeld-out one-step-ahead (chronological split):")
    print(f"  GRU : MAE={m_ml['mae_cqi']:.3f} CQI  MSE={m_ml['mse_cqi']:.3f}  MSE={m_ml['mse_db']:.2f} dB  "
          f"median={m_ml['median']:.3f} p95={m_ml['p95']:.3f}  (n={m_ml['n']})")
    print(f"  ZOH : MAE={m_zoh['mae_cqi']:.3f} CQI  MSE={m_zoh['mse_cqi']:.3f}  MSE={m_zoh['mse_db']:.2f} dB")
    print(f"  => {'GRU beats ZOH' if m_ml['mae_cqi'] < m_zoh['mae_cqi'] else 'ZOH >= GRU (no predictive gain)'}")

    if args.inc_out or args.model_out:
        a = arrays(gru)
        meta = {
            "sources": [os.path.basename(p) for p in paths],
            "windowed_samples": len(y),
            "held_out_mae_cqi": m_ml["mae_cqi"],
            "held_out_mse_db": m_ml["mse_db"],
            "zoh_mae_cqi": m_zoh["mae_cqi"],
            "hidden": args.hidden,
        }
        if args.inc_out:
            if args.inc_out.endswith(".model") or args.inc_out.endswith(".json"):
                sys.exit(f"refusing to write a generated C++ header to a data path: {args.inc_out}")
            export_inc(a, mu, sigma, args.window_size, args.hidden, args.t_out, args.inc_out)
            print(f"\nsaved compiled-in seed header -> {args.inc_out}")
        if args.model_out:
            os.makedirs(os.path.dirname(args.model_out) or ".", exist_ok=True)
            export_model_file(a, mu, sigma, args.window_size, args.hidden, args.t_out, args.model_out, meta)
            print(f"saved runtime override model -> {args.model_out}")

if __name__ == "__main__":
    main()
